export const REQUEST_DATA = 'REQUEST_DATA'
export const RECEIVE_DATA = 'RECEIVE_DATA'
export const REQUEST_CAMERA_INFO = 'REQUEST_CAMERA_INFO'
export const RECEIVE_CAMERA_INFO = 'RECEIVE_CAMERA_INFO'

